version: '2'

services:

  db:
    environment:
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
    image: postgres:9.4
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: backend
    command: ../wait-for db:5432 -- go run main.go
    environment:
      DATABASE_URL: postgres://demo:demo@db/demo
    ports:
      - 9000:80
    depends_on:
      - db
volumes:
  dbdata: